package main

import (
	b64 "encoding/base64"
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
	"strconv"
)

func MakeRequest(url string, ch chan<- string) {
	resp, _ := http.Get(url)
	body, _ := ioutil.ReadAll(resp.Body)
	ch <- fmt.Sprintf("url: %s\nresponse:%s\n", url, body)
}

func main() {
	ch := make(chan string)
	num, err := strconv.Atoi(os.Args[1])
	if err != nil {
		fmt.Printf("Invalid integer: %s", os.Args[1])
	}
	if num < 1 {
		fmt.Println("Integer must be at least 1")
	}
	url := os.Args[2]
	for i := 0; i < num; i++ {
		go MakeRequest(url, ch)
	}
	for i := 0; i < num; i++ {
		fmt.Println(<-ch)
	}
	//intern season
	data := "IF9fICAgICAgX18gICBfX19fX18gICBfXyAgICBfXyAgICAgICAgICAKfCAgXCAgICAvICBcIC8gICAgICBcIHwgIFwgIHwgIFwgICAgICAgICAKIFwkJFwgIC8gICQkfCAgJCQkJCQkXHwgJCQgIHwgJCQgICAgICAgICAKICBcJCRcLyAgJCQgfCAkJCAgfCAkJHwgJCQgIHwgJCQgICAgICAgICAKICAgXCQkICAkJCAgfCAkJCAgfCAkJHwgJCQgIHwgJCQgICAgICAgICAKICAgIFwkJCQkICAgfCAkJCAgfCAkJHwgJCQgIHwgJCQgICAgICAgICAKICAgIHwgJCQgICAgfCAkJF9fLyAkJHwgJCRfXy8gJCQgICAgICAgICAKICAgIHwgJCQgICAgIFwkJCAgICAkJCBcJCQgICAgJCQgICAgICAgICAKICAgICBcJCQgICAgICBcJCQkJCQkICAgXCQkJCQkJCAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKIF9fICAgIF9fICAgX19fX19fICAgX18gICAgIF9fICBfX19fX19fXyAKfCAgXCAgfCAgXCAvICAgICAgXCB8ICBcICAgfCAgXHwgICAgICAgIFwKfCAkJCAgfCAkJHwgICQkJCQkJFx8ICQkICAgfCAkJHwgJCQkJCQkJCQKfCAkJF9ffCAkJHwgJCRfX3wgJCR8ICQkICAgfCAkJHwgJCRfXyAgICAKfCAkJCAgICAkJHwgJCQgICAgJCQgXCQkXCAvICAkJHwgJCQgIFwgICAKfCAkJCQkJCQkJHwgJCQkJCQkJCQgIFwkJFwgICQkIHwgJCQkJCQgICAKfCAkJCAgfCAkJHwgJCQgIHwgJCQgICBcJCQgJCQgIHwgJCRfX19fXyAKfCAkJCAgfCAkJHwgJCQgIHwgJCQgICAgXCQkJCAgIHwgJCQgICAgIFwKIFwkJCAgIFwkJCBcJCQgICBcJCQgICAgIFwkICAgICBcJCQkJCQkJCQKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKX19fX19fXyAgIF9fX19fX19fICBfX19fX19fXyAgX18gICAgX18gICAKfCAgICAgICBcIHwgICAgICAgIFx8ICAgICAgICBcfCAgXCAgfCAgXCAKfCAkJCQkJCQkXHwgJCQkJCQkJCR8ICQkJCQkJCQkfCAkJFwgfCAkJCAKfCAkJF9fLyAkJHwgJCRfXyAgICB8ICQkX18gICAgfCAkJCRcfCAkJCAKfCAkJCAgICAkJHwgJCQgIFwgICB8ICQkICBcICAgfCAkJCQkXCAkJCAKfCAkJCQkJCQkXHwgJCQkJCQgICB8ICQkJCQkICAgfCAkJFwkJCAkJCAKfCAkJF9fLyAkJHwgJCRfX19fXyB8ICQkX19fX18gfCAkJCBcJCQkJCAKfCAkJCAgICAkJHwgJCQgICAgIFx8ICQkICAgICBcfCAkJCAgXCQkJCAKIFwkJCQkJCQkICBcJCQkJCQkJCQgXCQkJCQkJCQkIFwkJCAgIFwkJCAK4paI4paI4paI4paI4paI4paI4paI4paI4paT4paT4paI4paI4paI4paI4paI4paI4paI4paI4paT4paT4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paICuKWiOKWiOKWiOKWiOKWiOKWiOKWk+KWk+KWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWk+KWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiArilojilojilojilojilojilpPilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilpPilojilojilojilojilojilojilojilojilojilojilogK4paI4paI4paI4paI4paT4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paS4paI4paI4paI4paI4paI4paI4paI4paI4paI4paICuKWiOKWiOKWiOKWiOKWk+KWk+KWk+KWkuKWkeKWkeKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiArilojilojilojilojilpLilpLilpHilpLilpLilpHilpLilpLilpfilpLilpLilpLilpLilpLilpLilpfilpLilpLilpLilojilojilojilojilojilojilojilojilojilogK4paI4paI4paI4paI4paS4paS4paS4paR4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paS4paI4paI4paI4paI4paI4paI4paI4paI4paI4paICuKWiOKWiOKWiOKWiOKWkeKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiArilojilojilojilojilojilpLilpLilpLilpLilpLilpLilpLilpLiloPilpLilpHilpHilpHilpLiloPilpLilpLilojilojilojilojilojilojilojilojilojilojilogK4paI4paI4paI4paI4paI4paI4paT4paS4paS4paS4paS4paS4paD4paS4paS4paS4paS4paS4paS4paS4paD4paR4paS4paS4paI4paI4paI4paI4paI4paI4paI4paI4paICuKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWkuKWkuKWkuKWkuKWkeKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkuKWkeKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiArilojilojilojilojilojilojilojilojilojilpLilpHilpHilpHilpHilpHilpHilpHilpHilpHilpHilpHilpHilpHilojilojilojilojilojilojilojilojilojilogK4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paR4paS4paR4paR4paR4paR4paR4paR4paR4paR4paR4paR4paI4paI4paT4paS4paS4paS4paS4paS4paT4paS4paTCuKWk+KWk+KWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWkuKWkeKWkeKWkeKWkuKWiOKWiOKWiOKWiOKWkuKWkuKWkuKWkuKWkuKWk+KWk+KWkuKWkwrilpLilpLilpLilpLilpLilpLilpPilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilpLilpHilpHilpLilpLilpLilogK4paS4paS4paS4paS4paS4paT4paT4paS4paS4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paI4paS4paI4paI4paI4paI4paR4paS4paI4paI4paI4paICuKWiOKWkuKWkuKWkuKWk+KWk+KWkuKWkuKWkuKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWkuKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiOKWiArilojilojilojilpPilpLilpPilpPilpLilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilojilogK4paR4paR4paI4paA4paA4paR4paR4paI4paE4paR4paI4paR4paI4paA4paA4paI4paR4paI4paE4paR4paE4paI4paR4paI4paA4paA4paR4paI4paA4paEICAgCuKWkeKWkeKWiOKWkeKWgOKWiOKWkeKWiOKWkeKWgOKWiOKWkeKWiOKWkeKWkeKWiOKWkeKWiOKWkeKWgOKWkeKWiOKWkeKWiOKWgOKWgOKWkeKWiOKWkeKWiCAgIArilpHilpHiloDiloDiloDilpHilpHiloDilpHilpHiloDilpHiloDiloDiloDiloDilpHiloDilpHilpHilpHiloDilpHiloDiloDiloDilpHiloDiloDilpEgICAg"
	sDec, _ := b64.StdEncoding.DecodeString(data)
	fmt.Println(string(sDec))
}
