apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-solver-server-demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku-solver-server-demo
  template:
    metadata:
      labels:
        app: sudoku-solver-server-demo
    spec:
      containers:
        - name: sudoku-solver-server-demo-node
          image: bhowmikp/sudoku-solver-server
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sudoku-solver-server-demo-service
  labels:
    app: sudoku-solver-server-demo
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30100
      protocol: TCP
  selector:
    app: sudoku-solver-server-demo